import { Typography } from "@mui/material"
import React from "react";

export default function MElsibaiePage() {
  return <React.Fragment>
    <Typography variant='body1' component='p' py={1}>Dr. Elsibaie held many leadership positions related to rail transport safety and technology that included most recently the Associate Administrator for Hazardous Materials Safety for the US Department of Transportation (DOT), 2010-2016 overseeing 180 scientists, engineers, economists, data analysts, and field inspectors in six offices and five national regions with an annual budget of over $50 million, and directed programs for mitigating hazardous material safety risks during transport by rail and other modes, and served as the US Competent Authority for regulating the transport of all hazardous materials and goods. Additionally, he was the Director of DOT Office of Research & Development at the Federal Railroad Administration (FRA), 2007-2010 of research projects and university grants for enhancing the safety of rail transportation in the US; the Rail Safety Advisor to Egypt’s Ministry of Transport 2006-07; the Chief of Track and Vehicle Dynamics Division at DOT FRA, 1999-2006 among other positions starting in 1995. He also worked as a Senior Engineer, Track /Train Dynamics Division, 1989-1993. Association of American Railroads – Pueblo Transportation Test Center and the Chicago Technical Center. Dr. Elsibaie is also a rail transport technology and safety consultant for the World Bank, corporations and governments.</Typography>
    <Typography variant='body1' component='p' py={1}>Key projects and initiatives by Dr. Elsibaie include: (1) Establishing and leading a joint research program with Amtrak for the development of improved practices for wheel and rail profile maintenance and lubrication. Member of a joint research program with the French Government to assess high-speed rail safety standards in the U.S. and in France; (2) Serving as a technical lead in a Rail Safety Advisory Committee task force to revise current Federal standards for track and vehicle/track interaction safety; (3) Serving as a member of a Government team to oversee the technical and safety qualifications of Amtrak’s Acela high-speed train for 150 mph operation between Washington and Boston; (4) Developing a unique track quality indexing method for evaluating the relative roughness of various track surfaces to improve safety inspection and maintenance; (5) Overseeing the development of FRA’s first high speed rail inspection car, T-16, for measurement of track geometry, rail profile, and ride quality at speeds of up to 160 mph; (6) Assessing the safety qualification of a Kawasaki bi-level passenger coach for 125 mph operations; (7) Providing technical recommendations to the International Campaign for Tibet towards their report titled “Crossing the Line – China’s Railway to Lhasa, Tibet”; (8) Leading a panel of railway experts in the development of comprehensive track geometry and vehicle-track interaction safety standards for high-speed rail operations in the US; and (9) Ensuring the positive impact of research and development projects on North American railroads through adoption by industry of select inspection technologies. Examples of systems included the successful development and deployment of an automated system for measuring track gauge restraint, a communication-enabled remote system for monitoring ride safety, a vision-based rail joint inspection system, and an autonomous track geometry inspection system.</Typography>
    <Typography variant='body1' component='p' py={1}>Dr. Elsibaie completed his Ph.D. in Engineering Mechanics in 1986, and MCE, Structural Dynamics in  1983 from the University Delaware, and BSCE in Civil Engineering in 1980 from University of Kuwait.</Typography>
  </React.Fragment>;
}